-- Demonstrativo de funcionários: julho/2026, período de 07/07 a 17/07.
-- Dados de vínculo, função, setor e formação importados para consulta municipal.

WITH escola AS (
  UPDATE escolas
  SET
    inep = '29055105',
    endereco = 'Várzea Grande',
    diretor_nome = 'Wellington Reis de Aquino'
  WHERE codigo_rede = '27'
  RETURNING id
), profissionais (
  nome_completo,
  tipo_vinculo,
  carga_horaria,
  cargo,
  setor,
  formacao,
  observacoes
) AS (
  VALUES
    ('Wellington Reis de Aquino', 'Efetivo', '20h', 'Diretor Escolar', 'Matutino / Vespertino', 'Especialização', NULL),
    ('Junior Souza Fernandes', 'Efetivo', '20h', 'Vice-diretor', 'Vespertino / Noturno', 'Especialização', 'Vice-direção 40 horas'),
    ('Bruna Bernarda da Silva', 'Contrato', '20h', 'Vice-diretora', NULL, 'Ensino Médio', NULL),
    ('Solange Maria de Araujo', 'Efetivo', '20h', 'Vice-diretora / Professora', 'Vespertino', 'Especialização', '20h vice-direção e 20h professora'),
    ('Adriana Araujo Nascimento', 'Efetivo', '20h', 'Coordenadora Pedagógica', 'Matutino / Vespertino', 'Especialização', '40 horas'),
    ('UG de Araújo Ferreira de Jesus', 'Efetivo', '20h', 'Coordenadora Pedagógica', 'Matutino / Vespertino', 'Superior cursando', '40 horas'),
    ('Geiza Gonçalves P. Santana', 'Efetivo', 'Serviços Gerais', 'Coordenadora Pedagógica', 'Matutino / Vespertino', 'Especialização', '40 horas'),
    ('Queila Regina Pereira M. dos Reis', 'Contrato', '40h', 'Coordenadora Pedagógica', 'Matutino / Vespertino', 'Superior', '40 horas'),
    ('Paula Moura Vidal da Silva', 'Contrato', '40h', 'Secretária Escolar', 'Matutino / Vespertino', 'Médio/Técnico', NULL),
    ('Henrique Maroto Oliveira', 'Contrato', '40h', 'Auxiliar Técnico de Secretaria', 'Matutino / Vespertino', 'Superior incompleto', NULL),
    ('Jacillara Pereira dos Santos', 'Contrato', '40h', 'Auxiliar de Secretaria', 'Matutino / Vespertino', 'Ensino Médio', NULL),
    ('Maria Tania dos Anjos Santos', 'Contrato', '40h', 'Assistente Social', NULL, 'Superior', 'Professora II / Assistente Social'),
    ('Elizangela Lopes da S. Souza', 'Efetivo', 'Serviços Gerais', 'Professora', '1º ano matutino', 'Superior', NULL),
    ('Cleonice da Silva Pereira', 'Contrato', '20h', 'Professora', '2º ano matutino', 'Magistério/Superior', NULL),
    ('Roneives Nunes de Almeida', 'Contrato', '20h', 'Professor', '3º ano matutino', 'Especialização', 'Gratificação contínua'),
    ('Jaully de Araújo Costa', 'Contrato', '20h', 'Professora', '4º ano matutino', 'Especialização', NULL),
    ('Ana Maria Moura Silva', 'Contrato', '20h', 'Professora', '5º ano matutino', 'Superior', NULL),
    ('Andressa Fernandes da Silva', 'Contrato', '20h', 'Professora', NULL, 'Superior', NULL),
    ('Maria Riquelma Lima da Cruz', 'Contrato', '20h', 'Professora Articuladora', 'AI - Matutino', 'Superior', NULL),
    ('Maria Raissa Pereira de Melo', 'Contrato', '20h', 'Professora Articuladora', 'AI - Matutino', 'Superior incompleto', NULL),
    ('Ana Keylla Santos de Jesus', 'Contrato', '20h', 'Professora Auxiliar', 'AI - Matutino', 'Superior incompleto', NULL),
    ('William Ferreira da Silva', 'Contrato', '20h', 'Professor', 'Matemática', 'Superior', NULL),
    ('Franciane da S. Castro Alves', 'Contrato', '20h', 'Professora', 'Ciências', 'Superior', NULL),
    ('Carolaine Ferreira da Silva', 'Contrato', '20h', 'Professora', 'Inglês/Arte', 'Superior', NULL),
    ('Thamires da Silva Santos', 'Contrato', '20h', 'Professora', 'Equidade', 'Superior', NULL),
    ('Eluiza de Moura Araujo', 'Contrato', '20h', 'Professora', 'História', 'Superior incompleto', 'Alterar contrato para professora'),
    ('Taline Serafim da Silva', 'Contrato', '20h', 'Professora', 'Português/Arte', 'Superior', '10 horas de aula extra contínua'),
    ('Ellen Fernanda de O. Almeida', 'Contrato', '20h', 'Professora', 'Geografia', 'Superior', NULL),
    ('Josimara Nunes de A. Santos', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 1º ano', 'Ensino Médio', NULL),
    ('Paula da Silva Guimarães', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 1º ano', 'Ensino Médio', NULL),
    ('Ana Claudia Costa da Silva', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 2º ano', 'Ensino Médio', NULL),
    ('Janderson Liedson Soares Araujo', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 2º ano', 'Ensino Fundamental incompleto', NULL),
    ('Nubia Silva Cardoso', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 2º ano', 'Ensino Fundamental incompleto', NULL),
    ('Suzana dos Santos Silva', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 2º ano', 'Magistério', NULL),
    ('Laryssa Morais B. de Almeida', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AI - 4º ano', 'Superior incompleto', NULL),
    ('Clésia Rios Santos', 'Contrato', '20h', 'Profissional de Apoio Pedagógico', 'AI - 5º ano', 'Ensino Médio', NULL),
    ('Sirlândia Nascimento da Silva', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AF - 6º ano', 'Ensino Médio', 'Início em 20/07/2026; distrato em 17/07/2026'),
    ('Leiliane Oliveira da Silva', 'Contrato', '40h', 'Profissional de Apoio Pedagógico', 'AF - 8º ano', 'Ensino Médio', NULL),
    ('Gisella Oliveira Miranda', 'Efetivo', '40h', 'Professora', 'Letramento Língua AI', 'Especialização', NULL),
    ('Lorena da Silva Santos', 'Contrato', '20h', 'Professora', 'Letramento Matemática AI', 'Superior incompleto', NULL),
    ('Ana Selma Miranda Maia', 'Efetivo', '40h', 'Professora', 'Letramento Língua AF', 'Especialização', NULL),
    ('Fernando de Jesus Pinto', 'Contrato', '20h', 'Professor', 'Letramento Matemática AF', 'Superior', '12 horas de aula extra contínua'),
    ('Rodrigues Fernandes da Silva', 'Contrato', '20h', 'Professor', 'Informática', 'Superior/Pedagogia', NULL),
    ('Jônatas Fernandes da Silva', 'Contrato', '20h', 'Professor', 'Empreendedorismo', 'Superior', NULL),
    ('Bianca Araujo da Silva', 'Contrato', '20h', 'Professora', 'Empreendedorismo', 'Superior incompleto', NULL),
    ('Letícia Ferreira da Silva', 'Contrato', '40h', 'Monitora de Esporte', 'Futsal/Atletismo', 'Ensino Médio', NULL),
    ('Newton Costa Santana', 'Contrato', '40h', 'Monitor de Esporte', 'Futsal/Atletismo', 'Ensino Médio', NULL),
    ('Clara Naama Cardoso dos Santos', 'Contrato', '40h', 'Monitor de Cultura', 'Teatro', 'Ensino Médio', NULL),
    ('Jadson Ribeiro da Silva', 'Contrato', '40h', 'Monitor de Cultura', 'Música', 'Superior', NULL),
    ('Wesley Alves da Silva', 'Contrato', '40h', 'Monitor de Esporte', 'Futsal/Atletismo', 'Ensino Médio', NULL),
    ('Igor Leal Ferreira', 'Contrato', '40h', 'Monitor de Cultura', 'Capoeira', 'Ensino Médio', NULL),
    ('Adailton da Silva Batista', 'Contrato', '40h', 'Monitor de Cultura', 'Capoeira', 'Ensino Médio', NULL),
    ('Adriana Lopes Silva', 'Contrato', '20h', 'Professora EJA', 'Cachimbo', 'Ensino Médio', NULL),
    ('Alane Bernardo da Silva', 'Contrato', '20h', 'Professora EJA', 'Várzea Grande', 'Superior incompleto', NULL),
    ('Cassiane de Almeida Silva', 'Contrato', '20h', 'Professora EJA', 'Brejo dos Paulos', 'Ensino Médio', NULL),
    ('Elane Santos de Carvalho', 'Contrato', '20h', 'Professora EJA', 'Cachimbo', 'Ensino Médio', NULL),
    ('Estefane Alves da Silva', 'Contrato', '20h', 'Professora EJA', 'Várzea Grande', 'Ensino Médio', NULL),
    ('Jeane Costa da Silva', 'Contrato', '20h', 'Professora EJA', 'Serrota', 'Ensino Médio', NULL),
    ('Tailane dos Anjos Santos', 'Contrato', '20h', 'Professora EJA', 'Cachimbo', 'Ensino Médio', NULL),
    ('Leila Oliveira da Silva', 'Contrato', '20h', 'Professora EJA', 'Várzea Grande', 'Ensino Médio', NULL),
    ('Lucas Cirquera da Silva', 'Contrato', '20h', 'Professora EJA', 'Pedrinhas', 'Ensino Médio', NULL),
    ('Marcos Rogério Gonçalves dos Reis', 'Efetivo', '20h', 'Servidor Escolar', 'Várzea Grande', 'Ensino Médio', NULL),
    ('Romilson Anunciação Santos', 'Contrato', '20h', 'Professora EJA', 'Serrota', 'Ensino Médio', NULL),
    ('Roseane Ferreira Costa', 'Contrato', '20h', 'Professora EJA', 'Cachoeira', 'Ensino Médio', NULL),
    ('Tatiane da Silva Santos', 'Contrato', '20h', 'Professora EJA', 'Várzea Grande', 'Ensino Médio', NULL),
    ('Oscar Maia Santos', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Porteiro', 'Ensino Médio', NULL),
    ('Maria Egnelzia da Silva', 'Efetivo', '40h', 'Cozinheira', 'Cozinha', NULL, NULL),
    ('Jucileide Pereira dos Santos', 'Efetivo', '40h', 'Cozinheira', 'Cozinha', NULL, NULL),
    ('Vilma Silva de Menezes', 'Contrato', '40h', 'Cozinheira', 'Cozinha', 'Ensino Médio', NULL),
    ('Jaiane da Silva Ferreira', 'Contrato', '40h', 'Cozinheira', 'Cozinha', 'Ensino Médio', NULL),
    ('Cheila Nunes dos S. Moura', 'Contrato', '40h', 'Cozinheira', 'Cozinha EJA', NULL, NULL),
    ('Sione de Oliveira Santana', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Servente', NULL, NULL),
    ('Marisa dos Santos Ferreira', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Servente', NULL, NULL),
    ('Mirian Nunes de Jesus', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Servente', 'Ensino Médio', NULL),
    ('Vanuzia da Silva Lima', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Auxiliar de Transporte/Servente', NULL, NULL),
    ('Maria Vanuza Nunes Araujo', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Servente', 'Ensino Médio', NULL),
    ('Iodete Alves Ferreira', 'Efetivo', '40h', 'Auxiliar de Serviços Gerais', 'Servente EJA', NULL, NULL),
    ('Ivone Nunes Almeida', 'Efetivo', '40h', 'Cozinheira', 'Servente', NULL, NULL),
    ('Ivonete Fernandes da Silva', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Auxiliar de Transporte/Servente', NULL, NULL),
    ('Luzinete Gonçalves da Silva', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Auxiliar de Transporte/Servente', NULL, NULL),
    ('Luzinete Gomes dos Santos', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Servente', NULL, NULL),
    ('Sileide da Silva Ferreira', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Servente EJA', 'Ensino Fundamental completo', NULL),
    ('Sione do Nascimento Silva Cardoso', 'Contrato', '40h', 'Auxiliar de Serviços Gerais', 'Servente', 'Ensino Fundamental completo', NULL)
)
INSERT INTO funcionarios_educacao (
  escola_id,
  nome_completo,
  cpf,
  cargo,
  tipo_vinculo,
  carga_horaria,
  setor,
  formacao,
  observacoes,
  ativo
)
SELECT
  escola.id,
  profissionais.nome_completo,
  NULL,
  profissionais.cargo,
  profissionais.tipo_vinculo,
  profissionais.carga_horaria,
  profissionais.setor,
  profissionais.formacao,
  profissionais.observacoes,
  TRUE
FROM escola
CROSS JOIN profissionais
ON CONFLICT (escola_id, LOWER(nome_completo))
DO UPDATE SET
  cargo = EXCLUDED.cargo,
  tipo_vinculo = EXCLUDED.tipo_vinculo,
  carga_horaria = EXCLUDED.carga_horaria,
  setor = EXCLUDED.setor,
  formacao = EXCLUDED.formacao,
  observacoes = EXCLUDED.observacoes,
  ativo = TRUE,
  atualizado_em = NOW();
