ALTER TABLE bens_patrimoniais
  ALTER COLUMN descricao TYPE TEXT,
  ADD COLUMN IF NOT EXISTS foto_nome VARCHAR(255),
  ADD COLUMN IF NOT EXISTS foto_mime VARCHAR(100),
  ADD COLUMN IF NOT EXISTS foto_tamanho INTEGER,
  ADD COLUMN IF NOT EXISTS foto_bytes BYTEA;
