import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../database.js';
import { authenticate } from '../middlewares/auth.js';
import { loadAccessContext } from '../middlewares/access.js';

const router=Router();
const profiles=new Set(['Super Administrador','Secretário Municipal de Educação','Técnico da Secretaria de Educação','Secretaria Administrativa da Educação']);
const strategic=new Set(['Super Administrador','Secretário Municipal de Educação']);
const situations=['Em uso','Estoque','Manutenção','Transferência','Inservível','Baixado'];
const conservation=['Novo','Bom','Regular','Ruim','Inservível'];
const photoSchema=z.object({nome:z.string().trim().min(1).max(255),dados:z.string().min(1)}).nullable().optional();
const schema=z.object({numeroPatrimonial:z.string().trim().min(2).max(60),descricao:z.string().trim().min(3).max(2000),categoria:z.string().trim().min(2).max(100),marcaModelo:z.string().trim().max(180).nullable().optional(),numeroSerie:z.string().trim().max(120).nullable().optional(),escolaId:z.coerce.number().int().positive().nullable().optional(),setor:z.string().trim().max(120).nullable().optional(),localizacao:z.string().trim().min(2).max(180),responsavelId:z.coerce.number().int().positive().nullable().optional(),estadoConservacao:z.enum(conservation),situacao:z.enum(situations),dataAquisicao:z.iso.date().nullable().optional(),valor:z.coerce.number().nonnegative().nullable().optional(),comDivergencia:z.boolean().optional().default(false),divergenciaDescricao:z.string().trim().max(2000).nullable().optional(),foto:photoSchema}).refine(v=>v.escolaId||v.setor,{message:'Informe a escola ou o setor responsável pelo bem.'});
const transferSchema=z.object({novaEscolaId:z.coerce.number().int().positive().nullable().optional(),novoSetor:z.string().trim().max(120).nullable().optional(),novaLocalizacao:z.string().trim().min(2).max(180),novoResponsavelId:z.coerce.number().int().positive().nullable().optional(),motivo:z.string().trim().min(5).max(2000)}).refine(v=>v.novaEscolaId||v.novoSetor,{message:'Informe a nova unidade ou setor.'});
function fail(statusCode,message){const error=new Error(message);error.statusCode=statusCode;throw error;}
function decodePhoto(photo){if(!photo)return null;const match=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(photo.dados);if(!match)fail(400,'Envie uma foto JPG, PNG ou WebP válida.');const bytes=Buffer.from(match[2],'base64');if(!bytes.length||bytes.length>5*1024*1024)fail(400,'A foto deve ter no máximo 5 MB.');return{nome:photo.nome,mime:match[1],tamanho:bytes.length,bytes};}
router.use(authenticate,loadAccessContext,(req,res,next)=>profiles.has(req.access?.perfil)?next():res.status(403).json({message:'Acesso exclusivo da gestão patrimonial municipal.'}));
function canValue(req){return strategic.has(req.access.perfil);}

router.get('/references',async(req,res,next)=>{try{const [schools,users]=await Promise.all([pool.query(`SELECT id,nome FROM escolas WHERE ativo=TRUE ORDER BY nome`),pool.query(`SELECT u.id,u.nome,t.nome AS perfil FROM usuarios u JOIN tipos_usuarios t ON t.id=u.tipo_usuario_id WHERE u.ativo=TRUE ORDER BY u.nome`)]);return res.json({escolas:schools.rows,responsaveis:users.rows,podeGerenciarValor:canValue(req)});}catch(e){return next(e);}});

router.get('/',async(req,res,next)=>{try{const showValue=canValue(req);const {rows}=await pool.query(`SELECT b.id,b.numero_patrimonial AS "numeroPatrimonial",b.descricao,b.categoria,b.marca_modelo AS "marcaModelo",b.numero_serie AS "numeroSerie",b.escola_id AS "escolaId",e.nome AS escola,b.setor,b.localizacao,b.responsavel_id AS "responsavelId",u.nome AS responsavel,b.estado_conservacao AS "estadoConservacao",b.situacao,b.data_aquisicao AS "dataAquisicao",CASE WHEN $1 THEN b.valor_aquisicao ELSE NULL END AS valor,b.com_divergencia AS "comDivergencia",b.divergencia_descricao AS "divergenciaDescricao",(b.foto_bytes IS NOT NULL) AS "temFoto",b.foto_nome AS "fotoNome",b.criado_em AS "criadoEm",b.atualizado_em AS "atualizadoEm",COALESCE((SELECT JSON_AGG(JSON_BUILD_OBJECT('id',h.id,'acao',h.acao,'descricao',h.descricao,'usuario',hu.nome,'dados',h.dados,'criadoEm',h.criado_em) ORDER BY h.criado_em DESC) FROM historico_bens_patrimoniais h LEFT JOIN usuarios hu ON hu.id=h.usuario_id WHERE h.bem_id=b.id),'[]'::json) AS historico FROM bens_patrimoniais b LEFT JOIN escolas e ON e.id=b.escola_id LEFT JOIN usuarios u ON u.id=b.responsavel_id ORDER BY b.atualizado_em DESC,b.id DESC`,[showValue]);const resumo={total:rows.length,emUso:rows.filter(i=>i.situacao==='Em uso').length,manutencao:rows.filter(i=>i.situacao==='Manutenção').length,divergencia:rows.filter(i=>i.comDivergencia).length};return res.json({dados:rows,resumo,podeGerenciarValor:showValue});}catch(e){return next(e);}});

router.get('/:id/photo',async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.id);const {rows}=await pool.query('SELECT foto_nome,foto_mime,foto_bytes FROM bens_patrimoniais WHERE id=$1',[id]);const photo=rows[0];if(!photo)fail(404,'Bem patrimonial não encontrado.');if(!photo.foto_bytes)fail(404,'Este bem não possui foto cadastrada.');const filename=(photo.foto_nome||'foto-do-bem').replace(/[\r\n"\\]/g,'_');res.set({'Content-Type':photo.foto_mime,'Content-Disposition':`inline; filename="${filename}"`,'Cache-Control':'private, no-store'});return res.send(photo.foto_bytes);}catch(e){return next(e);}});

router.post('/',async(req,res,next)=>{const client=await pool.connect();try{const data=schema.parse(req.body);const photo=decodePhoto(data.foto);if(data.valor!=null&&!canValue(req))fail(403,'Seu perfil não está autorizado a registrar valores patrimoniais.');await client.query('BEGIN');const {rows}=await client.query(`INSERT INTO bens_patrimoniais(numero_patrimonial,descricao,categoria,marca_modelo,numero_serie,escola_id,setor,localizacao,responsavel_id,estado_conservacao,situacao,data_aquisicao,valor_aquisicao,com_divergencia,divergencia_descricao,foto_nome,foto_mime,foto_tamanho,foto_bytes,criado_por,atualizado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$20) RETURNING id`,[data.numeroPatrimonial,data.descricao,data.categoria,data.marcaModelo||null,data.numeroSerie||null,data.escolaId||null,data.setor||null,data.localizacao,data.responsavelId||null,data.estadoConservacao,data.situacao,data.dataAquisicao||null,data.valor??null,data.comDivergencia,data.divergenciaDescricao||null,photo?.nome||null,photo?.mime||null,photo?.tamanho||null,photo?.bytes||null,req.access.userId]);await client.query(`INSERT INTO historico_bens_patrimoniais(bem_id,usuario_id,acao,descricao,dados) VALUES($1,$2,'cadastrado',$3,$4::jsonb)`,[rows[0].id,req.access.userId,'Bem cadastrado no patrimônio municipal.',JSON.stringify({numeroPatrimonial:data.numeroPatrimonial,situacao:data.situacao,escolaId:data.escolaId||null,setor:data.setor||null,fotoAdicionada:Boolean(photo)})]);await client.query('COMMIT');return res.status(201).json({id:rows[0].id,message:'Bem patrimonial cadastrado com sucesso.'});}catch(e){await client.query('ROLLBACK');return next(e);}finally{client.release();}});

router.patch('/:id',async(req,res,next)=>{const client=await pool.connect();try{const id=z.coerce.number().int().positive().parse(req.params.id);const data=schema.parse(req.body);const photo=decodePhoto(data.foto);if(data.valor!=null&&!canValue(req))fail(403,'Seu perfil não está autorizado a alterar valores patrimoniais.');await client.query('BEGIN');const found=await client.query('SELECT * FROM bens_patrimoniais WHERE id=$1 FOR UPDATE',[id]);if(!found.rows[0])fail(404,'Bem patrimonial não encontrado.');await client.query(`UPDATE bens_patrimoniais SET numero_patrimonial=$1,descricao=$2,categoria=$3,marca_modelo=$4,numero_serie=$5,escola_id=$6,setor=$7,localizacao=$8,responsavel_id=$9,estado_conservacao=$10,situacao=$11,data_aquisicao=$12,valor_aquisicao=CASE WHEN $13 THEN $14 ELSE valor_aquisicao END,com_divergencia=$15,divergencia_descricao=$16,foto_nome=CASE WHEN $17 THEN $18 ELSE foto_nome END,foto_mime=CASE WHEN $17 THEN $19 ELSE foto_mime END,foto_tamanho=CASE WHEN $17 THEN $20 ELSE foto_tamanho END,foto_bytes=CASE WHEN $17 THEN $21 ELSE foto_bytes END,atualizado_por=$22,atualizado_em=NOW() WHERE id=$23`,[data.numeroPatrimonial,data.descricao,data.categoria,data.marcaModelo||null,data.numeroSerie||null,data.escolaId||null,data.setor||null,data.localizacao,data.responsavelId||null,data.estadoConservacao,data.situacao,data.dataAquisicao||null,canValue(req),data.valor??null,data.comDivergencia,data.divergenciaDescricao||null,Boolean(photo),photo?.nome||null,photo?.mime||null,photo?.tamanho||null,photo?.bytes||null,req.access.userId,id]);await client.query(`INSERT INTO historico_bens_patrimoniais(bem_id,usuario_id,acao,descricao,dados) VALUES($1,$2,'editado',$3,$4::jsonb)`,[id,req.access.userId,'Cadastro patrimonial atualizado.',JSON.stringify({situacaoAnterior:found.rows[0].situacao,situacaoNova:data.situacao,divergencia:data.comDivergencia,fotoAtualizada:Boolean(photo)})]);await client.query('COMMIT');return res.json({id,message:'Bem patrimonial atualizado.'});}catch(e){await client.query('ROLLBACK');return next(e);}finally{client.release();}});

router.post('/:id/transfer',async(req,res,next)=>{const client=await pool.connect();try{const id=z.coerce.number().int().positive().parse(req.params.id);const data=transferSchema.parse(req.body);await client.query('BEGIN');const found=await client.query('SELECT * FROM bens_patrimoniais WHERE id=$1 FOR UPDATE',[id]);const item=found.rows[0];if(!item)fail(404,'Bem patrimonial não encontrado.');if(item.situacao==='Baixado')fail(409,'Um bem baixado não pode ser transferido.');await client.query(`UPDATE bens_patrimoniais SET escola_id=$1,setor=$2,localizacao=$3,responsavel_id=$4,situacao='Em uso',atualizado_por=$5,atualizado_em=NOW() WHERE id=$6`,[data.novaEscolaId||null,data.novoSetor||null,data.novaLocalizacao,data.novoResponsavelId||null,req.access.userId,id]);await client.query(`INSERT INTO historico_bens_patrimoniais(bem_id,usuario_id,acao,descricao,dados) VALUES($1,$2,'transferido',$3,$4::jsonb)`,[id,req.access.userId,data.motivo,JSON.stringify({origem:{escolaId:item.escola_id,setor:item.setor,localizacao:item.localizacao,responsavelId:item.responsavel_id},destino:{escolaId:data.novaEscolaId||null,setor:data.novoSetor||null,localizacao:data.novaLocalizacao,responsavelId:data.novoResponsavelId||null}})]);await client.query('COMMIT');return res.json({id,message:'Transferência confirmada e registrada no histórico.'});}catch(e){await client.query('ROLLBACK');return next(e);}finally{client.release();}});

export default router;
