import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../database.js';
import { authenticate } from '../middlewares/auth.js';
import { loadAccessContext } from '../middlewares/access.js';

const router=Router();
const profiles=new Set(['Super Administrador','Secretário Municipal de Educação','Técnico da Secretaria de Educação','Secretaria Administrativa da Educação']);
const strategic=new Set(['Super Administrador','Secretário Municipal de Educação']);
const attachment=z.object({etapa:z.enum(['Solicitação','Antes','Depois','Comprovação']),nome:z.string().trim().min(1).max(255),dados:z.string().min(1)}).nullable().optional();
const createSchema=z.object({origem:z.enum(['Escola','Equipamento','Patrimônio','Veículo']),escolaId:z.coerce.number().int().positive().nullable().optional(),bemId:z.coerce.number().int().positive().nullable().optional(),veiculoId:z.coerce.number().int().positive().nullable().optional(),demandaId:z.coerce.number().int().positive().nullable().optional(),itemLocal:z.string().trim().min(3).max(255),problema:z.string().trim().min(5).max(4000),prioridade:z.enum(['Baixa','Normal','Alta','Urgente']),prazo:z.iso.date().nullable().optional(),custo:z.coerce.number().nonnegative().nullable().optional(),anexo:attachment});
const actionSchema=z.object({acao:z.enum(['triar','atribuir','iniciar','comprovar','concluir','cancelar']),responsavelId:z.coerce.number().int().positive().nullable().optional(),prazo:z.iso.date().nullable().optional(),custo:z.coerce.number().nonnegative().nullable().optional(),descricao:z.string().trim().min(3).max(3000),anexo:attachment});
function fail(statusCode,message){const error=new Error(message);error.statusCode=statusCode;throw error;}
function decode(file){if(!file)return null;const match=/^data:(application\/pdf|image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(file.dados);if(!match)fail(400,'Envie PDF, JPG, PNG ou WebP válido.');const bytes=Buffer.from(match[2],'base64');if(!bytes.length||bytes.length>5*1024*1024)fail(400,'O arquivo deve ter no máximo 5 MB.');return{...file,mime:match[1],bytes,tamanho:bytes.length};}
function canCost(request){return strategic.has(request.access.perfil);}
router.use(authenticate,loadAccessContext,(request,response,next)=>profiles.has(request.access?.perfil)?next():response.status(403).json({message:'Acesso exclusivo da gestão administrativa municipal.'}));

router.get('/references',async(request,response,next)=>{try{const [schools,assets,vehicles,users]=await Promise.all([pool.query(`SELECT id,nome FROM escolas WHERE ativo=TRUE ORDER BY nome`),pool.query(`SELECT id,numero_patrimonial AS "numeroPatrimonial",descricao,escola_id AS "escolaId" FROM bens_patrimoniais WHERE situacao<>'Baixado' ORDER BY descricao`),pool.query(`SELECT id,prefixo,placa,marca_modelo AS "marcaModelo" FROM veiculos_transporte WHERE ativo=TRUE ORDER BY prefixo`),pool.query(`SELECT u.id,u.nome,t.nome AS perfil FROM usuarios u JOIN tipos_usuarios t ON t.id=u.tipo_usuario_id WHERE u.ativo=TRUE AND t.nome NOT IN ('Aluno') ORDER BY u.nome`)]);return response.json({escolas:schools.rows,bens:assets.rows,veiculos:vehicles.rows,responsaveis:users.rows,podeGerenciarCusto:canCost(request)});}catch(error){return next(error);}});

router.get('/',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT o.id,o.protocolo,o.origem,o.escola_id AS "escolaId",e.nome AS escola,o.bem_id AS "bemId",b.numero_patrimonial AS "numeroPatrimonial",o.veiculo_id AS "veiculoId",v.prefixo AS veiculo,v.placa,o.demanda_id AS "demandaId",o.item_local AS "itemLocal",o.problema,o.prioridade,o.status,o.responsavel_id AS "responsavelId",u.nome AS responsavel,o.prazo,CASE WHEN $1 THEN o.custo ELSE NULL END AS custo,o.criado_em AS "criadoEm",o.atualizado_em AS "atualizadoEm",COALESCE((SELECT JSON_AGG(JSON_BUILD_OBJECT('id',a.id,'etapa',a.etapa,'nome',a.nome,'mime',a.mime,'tamanho',a.tamanho,'criadoEm',a.criado_em) ORDER BY a.criado_em) FROM anexos_ordens_manutencao a WHERE a.ordem_id=o.id),'[]'::json) AS anexos,COALESCE((SELECT JSON_AGG(JSON_BUILD_OBJECT('id',h.id,'statusAnterior',h.status_anterior,'statusNovo',h.status_novo,'descricao',h.descricao,'usuario',hu.nome,'criadoEm',h.criado_em) ORDER BY h.criado_em DESC) FROM historico_ordens_manutencao h LEFT JOIN usuarios hu ON hu.id=h.usuario_id WHERE h.ordem_id=o.id),'[]'::json) AS historico FROM ordens_manutencao o LEFT JOIN escolas e ON e.id=o.escola_id LEFT JOIN bens_patrimoniais b ON b.id=o.bem_id LEFT JOIN veiculos_transporte v ON v.id=o.veiculo_id LEFT JOIN usuarios u ON u.id=o.responsavel_id ORDER BY CASE o.prioridade WHEN 'Urgente' THEN 1 WHEN 'Alta' THEN 2 WHEN 'Normal' THEN 3 ELSE 4 END,o.criado_em DESC`,[canCost(request)]);return response.json({dados:rows,resumo:{abertas:rows.filter(i=>!['Concluída','Cancelada'].includes(i.status)).length,urgentes:rows.filter(i=>i.prioridade==='Urgente'&&!['Concluída','Cancelada'].includes(i.status)).length,execucao:rows.filter(i=>i.status==='Em execução').length,atrasadas:rows.filter(i=>i.prazo&&new Date(i.prazo)<new Date()&&!['Concluída','Cancelada'].includes(i.status)).length},podeGerenciarCusto:canCost(request)});}catch(error){return next(error);}});

router.get('/:id/attachments/:attachmentId',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT nome,mime,conteudo FROM anexos_ordens_manutencao WHERE id=$1 AND ordem_id=$2`,[request.params.attachmentId,request.params.id]);const file=rows[0];if(!file)fail(404,'Anexo não encontrado.');response.set({'Content-Type':file.mime,'Content-Disposition':`attachment; filename="${file.nome.replace(/[\r\n"\\]/g,'_')}"`,'Cache-Control':'private, no-store'});return response.send(file.conteudo);}catch(error){return next(error);}});

router.post('/',async(request,response,next)=>{const client=await pool.connect();try{const data=createSchema.parse(request.body);if(data.custo!=null&&!canCost(request))fail(403,'Seu perfil não pode registrar custos.');if(data.origem==='Patrimônio'&&!data.bemId)fail(400,'Selecione o bem patrimonial.');if(data.origem==='Veículo'&&!data.veiculoId)fail(400,'Selecione o veículo.');const file=decode(data.anexo);await client.query('BEGIN');const protocol=`MAN-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`;const {rows}=await client.query(`INSERT INTO ordens_manutencao(protocolo,origem,escola_id,bem_id,veiculo_id,demanda_id,item_local,problema,prioridade,prazo,custo,criado_por) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,[protocol,data.origem,data.escolaId||null,data.bemId||null,data.veiculoId||null,data.demandaId||null,data.itemLocal,data.problema,data.prioridade,data.prazo||null,data.custo??null,request.access.userId]);await client.query(`INSERT INTO historico_ordens_manutencao(ordem_id,usuario_id,status_novo,descricao) VALUES($1,$2,'Solicitação','Ordem de manutenção registrada.')`,[rows[0].id,request.access.userId]);if(file)await client.query(`INSERT INTO anexos_ordens_manutencao(ordem_id,etapa,nome,mime,tamanho,conteudo,enviado_por) VALUES($1,$2,$3,$4,$5,$6,$7)`,[rows[0].id,file.etapa,file.nome,file.mime,file.tamanho,file.bytes,request.access.userId]);await client.query('COMMIT');return response.status(201).json({id:rows[0].id,protocolo:protocol,message:'Ordem de manutenção criada.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});

router.patch('/:id',async(request,response,next)=>{const client=await pool.connect();try{const id=z.coerce.number().int().positive().parse(request.params.id);const data=actionSchema.parse(request.body);if(data.custo!=null&&!canCost(request))fail(403,'Seu perfil não pode registrar custos.');const file=decode(data.anexo);await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM ordens_manutencao WHERE id=$1 FOR UPDATE',[id]);const order=rows[0];if(!order)fail(404,'Ordem não encontrada.');const rules={triar:['Solicitação','Triagem'],atribuir:['Triagem','Atribuída'],iniciar:['Atribuída','Em execução'],comprovar:['Em execução','Aguardando comprovação'],concluir:['Aguardando comprovação','Concluída'],cancelar:[order.status,'Cancelada']};const rule=rules[data.acao];if(data.acao!=='cancelar'&&order.status!==rule[0])fail(409,`Ação indisponível para ordem em “${order.status}”.`);if(data.acao==='atribuir'&&!data.responsavelId)fail(400,'Selecione o responsável.');if(data.acao==='comprovar'&&(!file||!['Depois','Comprovação'].includes(file.etapa)))fail(400,'Envie a foto depois ou o comprovante da execução.');await client.query(`UPDATE ordens_manutencao SET status=$1,responsavel_id=COALESCE($2,responsavel_id),prazo=COALESCE($3,prazo),custo=CASE WHEN $4 THEN COALESCE($5,custo) ELSE custo END,atualizado_em=NOW(),concluido_em=CASE WHEN $1='Concluída' THEN NOW() ELSE concluido_em END WHERE id=$6`,[rule[1],data.responsavelId||null,data.prazo||null,canCost(request),data.custo??null,id]);if(file)await client.query(`INSERT INTO anexos_ordens_manutencao(ordem_id,etapa,nome,mime,tamanho,conteudo,enviado_por) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,file.etapa,file.nome,file.mime,file.tamanho,file.bytes,request.access.userId]);await client.query(`INSERT INTO historico_ordens_manutencao(ordem_id,usuario_id,status_anterior,status_novo,descricao) VALUES($1,$2,$3,$4,$5)`,[id,request.access.userId,order.status,rule[1],data.descricao]);await client.query('COMMIT');return response.json({id,status:rule[1],message:'Ordem de manutenção atualizada.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});
export default router;
