import { Router } from 'express';
import { pool } from '../database.js';
import { authenticate } from '../middlewares/auth.js';
import { loadAccessContext } from '../middlewares/access.js';

const router = Router();
router.use(authenticate, loadAccessContext);
router.use((request, response, next) => {
  if (request.access?.perfil !== 'Professor') return response.status(403).json({ message: 'Acesso exclusivo do perfil Professor.' });
  return next();
});

router.get('/dashboard', async (request, response, next) => {
  try {
    const professor = await pool.query(`SELECT p.id, p.nome_completo AS nome, p.especialidade AS disciplina FROM professores p WHERE p.usuario_id = $1 AND p.ativo = TRUE LIMIT 1`, [request.access.userId]);
    const teacher = professor.rows[0];
    if (!teacher) return response.json({ professor: null, turmas: [], resumo: { turmas: 0, alunos: 0, aulas: 0, atividades: 0, avaliacoes: 0, faltasHoje: 0 } });
    const classes = await pool.query(`SELECT t.id, t.nome, t.serie_ano AS "serieAno", t.turno, t.sala, tp.componente_curricular AS "componenteCurricular", COUNT(DISTINCT m.id)::INTEGER AS "alunosMatriculados" FROM turma_professores tp JOIN turmas t ON t.id = tp.turma_id AND t.status = 'Ativa' LEFT JOIN matriculas m ON m.turma_id = t.id AND m.status = 'Ativa' WHERE tp.professor_id = $1 GROUP BY t.id, t.nome, t.serie_ano, t.turno, t.sala, tp.componente_curricular ORDER BY t.nome`, [teacher.id]);
    const students = classes.rows.reduce((total, item) => total + Number(item.alunosMatriculados || 0), 0);
    return response.json({ professor: { id: teacher.id, nome: teacher.nome, disciplina: teacher.disciplina || null }, turmas: classes.rows, resumo: { turmas: classes.rowCount, alunos: students, aulas: 0, atividades: 0, avaliacoes: 0, faltasHoje: 0 } });
  } catch (error) { return next(error); }
});

router.get('/classes/:id/students', async (request, response, next) => {
 try {
  const classId=Number(request.params.id);
  const allowed=await pool.query(`SELECT 1 FROM professores p JOIN turma_professores tp ON tp.professor_id=p.id WHERE p.usuario_id=$1 AND tp.turma_id=$2 AND p.ativo=TRUE`,[request.access.userId,classId]);
  if(!allowed.rows[0]) return response.status(403).json({message:'Esta turma não está atribuída ao professor.'});
  const {rows}=await pool.query(`SELECT a.id,a.nome_completo AS nome,a.nome_social AS "nomeSocial",m.id AS "matriculaId",m.status FROM matriculas m JOIN alunos a ON a.id=m.aluno_id WHERE m.turma_id=$1 AND m.status='Ativa' ORDER BY a.nome_completo`,[classId]);
  return response.json(rows);
 } catch(error){ return next(error); }
});

router.get('/students/:studentId/history', async (request,response,next)=>{
 try {
  const studentId=Number(request.params.studentId); const classId=Number(request.query.turmaId);
  const access=await pool.query(`SELECT p.id AS professor_id,tp.componente_curricular FROM professores p JOIN turma_professores tp ON tp.professor_id=p.id JOIN matriculas m ON m.turma_id=tp.turma_id WHERE p.usuario_id=$1 AND m.aluno_id=$2 AND tp.turma_id=$3 AND p.ativo=TRUE AND m.status='Ativa' LIMIT 1`,[request.access.userId,studentId,classId]);
  if(!access.rows[0]) return response.status(403).json({message:'Aluno não pertence a uma turma atribuída ao professor.'});
  const [student,notes,absences,activities]=await Promise.all([
   pool.query(`SELECT id,nome_completo AS nome,nome_social AS "nomeSocial",data_nascimento AS "dataNascimento" FROM alunos WHERE id=$1`,[studentId]),
   pool.query(`SELECT avaliacao,nota::float8,data_avaliacao AS data,componente_curricular AS disciplina FROM notas_alunos WHERE aluno_id=$1 AND turma_id=$2 AND professor_id=$3 ORDER BY data_avaliacao DESC`,[studentId,classId,access.rows[0].professor_id]),
   pool.query(`SELECT data_aula AS data,quantidade,justificada,componente_curricular AS disciplina FROM faltas_alunos WHERE aluno_id=$1 AND turma_id=$2 AND professor_id=$3 ORDER BY data_aula DESC`,[studentId,classId,access.rows[0].professor_id]),
   pool.query(`SELECT titulo,prazo,status FROM atividades_alunos WHERE aluno_id=$1 AND turma_id=$2 AND professor_id=$3 ORDER BY prazo`,[studentId,classId,access.rows[0].professor_id])
  ]);
  return response.json({aluno:student.rows[0],notas:notes.rows,faltas:absences.rows,atividades:activities.rows,resumo:{media:notes.rows.length?notes.rows.reduce((s,n)=>s+Number(n.nota),0)/notes.rows.length:null,totalFaltas:absences.rows.reduce((s,f)=>s+Number(f.quantidade),0),pendencias:activities.rows.filter(a=>a.status==='Pendente'||a.status==='Atrasada').length}});
 } catch(error){return next(error);}
});

router.get('/diaries', async (request,response,next)=>{
 try { const {rows}=await pool.query(`SELECT d.id,d.turma_id AS "turmaId",t.nome AS turma,d.componente_curricular AS disciplina,d.data_aula AS data,d.quantidade_aulas AS "quantidadeAulas",d.conteudo,d.metodologia,d.observacoes,COUNT(f.aluno_id) FILTER(WHERE f.presente=FALSE)::INTEGER AS faltas FROM diarios_classe d JOIN professores p ON p.id=d.professor_id JOIN turmas t ON t.id=d.turma_id LEFT JOIN diario_frequencias f ON f.diario_id=d.id WHERE p.usuario_id=$1 GROUP BY d.id,t.nome ORDER BY d.data_aula DESC,d.id DESC LIMIT 30`,[request.access.userId]); return response.json(rows); } catch(error){return next(error);}
});

router.post('/diaries', async (request,response,next)=>{
 const client=await pool.connect();
 try { const {turmaId,data,quantidadeAulas,conteudo,metodologia,observacoes,frequencias}=request.body;
  const linked=await client.query(`SELECT p.id AS professor_id,tp.componente_curricular FROM professores p JOIN turma_professores tp ON tp.professor_id=p.id WHERE p.usuario_id=$1 AND tp.turma_id=$2 AND p.ativo=TRUE LIMIT 1`,[request.access.userId,Number(turmaId)]);
  if(!linked.rows[0]) return response.status(403).json({message:'Turma não atribuída ao professor.'});
  if(!data||!String(conteudo||'').trim()) return response.status(400).json({message:'Informe a data e o conteúdo ministrado.'});
  await client.query('BEGIN'); const teacher=linked.rows[0];
  const saved=await client.query(`INSERT INTO diarios_classe(turma_id,professor_id,componente_curricular,data_aula,quantidade_aulas,conteudo,metodologia,observacoes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(turma_id,professor_id,componente_curricular,data_aula) DO UPDATE SET quantidade_aulas=EXCLUDED.quantidade_aulas,conteudo=EXCLUDED.conteudo,metodologia=EXCLUDED.metodologia,observacoes=EXCLUDED.observacoes,atualizado_em=NOW() RETURNING id`,[turmaId,teacher.professor_id,teacher.componente_curricular,data,Number(quantidadeAulas||1),String(conteudo).trim(),metodologia||null,observacoes||null]);
  const diaryId=saved.rows[0].id; await client.query('DELETE FROM diario_frequencias WHERE diario_id=$1',[diaryId]);
  for(const item of Array.isArray(frequencias)?frequencias:[]){ const enrollment=await client.query(`SELECT 1 FROM matriculas WHERE aluno_id=$1 AND turma_id=$2 AND status='Ativa'`,[item.alunoId,turmaId]); if(!enrollment.rows[0]) throw Object.assign(new Error('Aluno fora da turma.'),{statusCode:403}); await client.query(`INSERT INTO diario_frequencias(diario_id,aluno_id,presente,justificada,observacao) VALUES($1,$2,$3,$4,$5)`,[diaryId,item.alunoId,item.presente!==false,Boolean(item.justificada),item.observacao||null]); if(item.presente===false){await client.query(`INSERT INTO faltas_alunos(aluno_id,turma_id,professor_id,componente_curricular,data_aula,quantidade,justificada) SELECT $1,$2,$3,$4,$5,1,$6 WHERE NOT EXISTS(SELECT 1 FROM faltas_alunos WHERE aluno_id=$1 AND turma_id=$2 AND professor_id=$3 AND data_aula=$5)`,[item.alunoId,turmaId,teacher.professor_id,teacher.componente_curricular,data,Boolean(item.justificada)]);} }
  await client.query('COMMIT'); return response.status(201).json({id:diaryId,message:'Diário salvo com sucesso.'});
 } catch(error){await client.query('ROLLBACK');return next(error);} finally{client.release();}
});

async function professorClass(request,classId){const result=await pool.query(`SELECT p.id AS professor_id,tp.componente_curricular FROM professores p JOIN turma_professores tp ON tp.professor_id=p.id WHERE p.usuario_id=$1 AND tp.turma_id=$2 AND p.ativo=TRUE LIMIT 1`,[request.access.userId,Number(classId)]);return result.rows[0];}

router.get('/gradebook/:classId',async(request,response,next)=>{try{const link=await professorClass(request,request.params.classId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});const [students,assessments,grades]=await Promise.all([pool.query(`SELECT a.id,a.nome_completo AS nome FROM matriculas m JOIN alunos a ON a.id=m.aluno_id WHERE m.turma_id=$1 AND m.status='Ativa' ORDER BY a.nome_completo`,[request.params.classId]),pool.query(`SELECT id,titulo,tipo,data_avaliacao AS data,valor_maximo::float8 AS "valorMaximo",bimestre FROM avaliacoes_professor WHERE turma_id=$1 AND professor_id=$2 ORDER BY data_avaliacao,id`,[request.params.classId,link.professor_id]),pool.query(`SELECT n.avaliacao_id AS "avaliacaoId",n.aluno_id AS "alunoId",n.pontos::float8 FROM notas_avaliacoes n JOIN avaliacoes_professor a ON a.id=n.avaliacao_id WHERE a.turma_id=$1 AND a.professor_id=$2`,[request.params.classId,link.professor_id])]);return response.json({alunos:students.rows,avaliacoes:assessments.rows,notas:grades.rows,mediaAprovacao:6});}catch(error){return next(error);}});

router.post('/gradebook/:classId/assessments',async(request,response,next)=>{try{const link=await professorClass(request,request.params.classId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});const {titulo,tipo,data,valorMaximo,bimestre}=request.body;if(!titulo||!data||Number(valorMaximo)<=0)return response.status(400).json({message:'Preencha os dados da avaliação.'});const total=await pool.query(`SELECT COALESCE(SUM(valor_maximo),0)::float8 AS total FROM avaliacoes_professor WHERE turma_id=$1 AND professor_id=$2 AND bimestre=$3`,[request.params.classId,link.professor_id,Number(bimestre||1)]);if(Number(total.rows[0].total)+Number(valorMaximo)>10)return response.status(400).json({message:'A soma das atividades do bimestre não pode ultrapassar 10 pontos.'});const {rows}=await pool.query(`INSERT INTO avaliacoes_professor(turma_id,professor_id,componente_curricular,titulo,tipo,data_avaliacao,valor_maximo,bimestre) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[request.params.classId,link.professor_id,link.componente_curricular,String(titulo).trim(),tipo||'Atividade',data,Number(valorMaximo),Number(bimestre||1)]);return response.status(201).json(rows[0]);}catch(error){return next(error);}});

router.put('/gradebook/:classId/grades',async(request,response,next)=>{const client=await pool.connect();try{const link=await professorClass(request,request.params.classId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});await client.query('BEGIN');for(const item of Array.isArray(request.body.notas)?request.body.notas:[]){const check=await client.query(`SELECT a.valor_maximo::float8 FROM avaliacoes_professor a JOIN matriculas m ON m.turma_id=a.turma_id AND m.aluno_id=$1 AND m.status='Ativa' WHERE a.id=$2 AND a.turma_id=$3 AND a.professor_id=$4`,[item.alunoId,item.avaliacaoId,request.params.classId,link.professor_id]);if(!check.rows[0])throw Object.assign(new Error('Nota fora da turma ou avaliação.'),{statusCode:403});if(Number(item.pontos)<0||Number(item.pontos)>Number(check.rows[0].valor_maximo))throw Object.assign(new Error('A nota ultrapassa o valor da atividade.'),{statusCode:400});await client.query(`INSERT INTO notas_avaliacoes(avaliacao_id,aluno_id,pontos) VALUES($1,$2,$3) ON CONFLICT(avaliacao_id,aluno_id) DO UPDATE SET pontos=EXCLUDED.pontos,atualizado_em=NOW()`,[item.avaliacaoId,item.alunoId,Number(item.pontos)]);}await client.query('COMMIT');return response.json({message:'Notas salvas com sucesso.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});

router.get('/lesson-plans',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT pl.id,pl.turma_id AS "turmaId",t.nome AS turma,pl.componente_curricular AS disciplina,pl.data_aula AS data,pl.bimestre,pl.quantidade_aulas AS "quantidadeAulas",pl.tema,pl.objetivos,pl.habilidades_bncc AS "habilidadesBncc",pl.conteudos,pl.metodologia,pl.recursos,pl.avaliacao,pl.adaptacoes_inclusivas AS "adaptacoesInclusivas",pl.tarefa_casa AS "tarefaCasa",pl.observacoes,pl.status FROM planejamentos_aula pl JOIN professores p ON p.id=pl.professor_id JOIN turmas t ON t.id=pl.turma_id WHERE p.usuario_id=$1 ORDER BY pl.data_aula DESC,pl.id DESC`,[request.access.userId]);return response.json(rows);}catch(error){return next(error);}});

router.post('/lesson-plans',async(request,response,next)=>{try{const d=request.body;const link=await professorClass(request,d.turmaId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});const required=['data','tema','objetivos','conteudos','metodologia','avaliacao'];for(const field of required){if(!String(d[field]||'').trim())return response.status(400).json({message:'Preencha todos os campos obrigatórios do planejamento.'});}const {rows}=await pool.query(`INSERT INTO planejamentos_aula(turma_id,professor_id,componente_curricular,data_aula,bimestre,quantidade_aulas,tema,objetivos,habilidades_bncc,conteudos,metodologia,recursos,avaliacao,adaptacoes_inclusivas,tarefa_casa,observacoes,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING id,status`,[d.turmaId,link.professor_id,link.componente_curricular,d.data,Number(d.bimestre||1),Number(d.quantidadeAulas||1),d.tema.trim(),d.objetivos.trim(),d.habilidadesBncc||null,d.conteudos.trim(),d.metodologia.trim(),d.recursos||null,d.avaliacao.trim(),d.adaptacoesInclusivas||null,d.tarefaCasa||null,d.observacoes||null,d.status||'Rascunho']);return response.status(201).json(rows[0]);}catch(error){return next(error);}});

router.put('/lesson-plans/:id',async(request,response,next)=>{try{const d=request.body;const owner=await pool.query(`SELECT pl.id,pl.turma_id FROM planejamentos_aula pl JOIN professores p ON p.id=pl.professor_id WHERE pl.id=$1 AND p.usuario_id=$2`,[request.params.id,request.access.userId]);if(!owner.rows[0])return response.status(403).json({message:'Planejamento não pertence ao professor.'});const link=await professorClass(request,d.turmaId||owner.rows[0].turma_id);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});const {rows}=await pool.query(`UPDATE planejamentos_aula SET turma_id=$1,componente_curricular=$2,data_aula=$3,bimestre=$4,quantidade_aulas=$5,tema=$6,objetivos=$7,habilidades_bncc=$8,conteudos=$9,metodologia=$10,recursos=$11,avaliacao=$12,adaptacoes_inclusivas=$13,tarefa_casa=$14,observacoes=$15,status=$16,atualizado_em=NOW() WHERE id=$17 RETURNING id,status`,[d.turmaId,link.componente_curricular,d.data,Number(d.bimestre),Number(d.quantidadeAulas),d.tema,d.objetivos,d.habilidadesBncc||null,d.conteudos,d.metodologia,d.recursos||null,d.avaliacao,d.adaptacoesInclusivas||null,d.tarefaCasa||null,d.observacoes||null,(d.status==='Enviado para aprovação'?'Enviado para aprovação':'Rascunho'),request.params.id]);return response.json(rows[0]);}catch(error){return next(error);}});

router.get('/schedule',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT h.id,h.turma_id AS "turmaId",t.nome AS turma,h.componente_curricular AS disciplina,h.dia_semana AS "diaSemana",TO_CHAR(h.hora_inicio,'HH24:MI') AS "horaInicio",TO_CHAR(h.hora_fim,'HH24:MI') AS "horaFim",h.sala FROM horarios_professor h JOIN professores p ON p.id=h.professor_id JOIN turmas t ON t.id=h.turma_id WHERE p.usuario_id=$1 AND h.ativo=TRUE ORDER BY h.dia_semana,h.hora_inicio`,[request.access.userId]);return response.json(rows);}catch(error){return next(error);}});

router.get('/activities',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT a.id,a.turma_id AS "turmaId",t.nome AS turma,a.componente_curricular AS disciplina,a.tipo,a.titulo,a.descricao,a.data_evento AS data,TO_CHAR(a.hora_inicio,'HH24:MI') AS "horaInicio",TO_CHAR(a.hora_fim,'HH24:MI') AS "horaFim",a.valor::float8,a.instrucoes,a.materiais,a.status FROM atividades_programadas a JOIN professores p ON p.id=a.professor_id JOIN turmas t ON t.id=a.turma_id WHERE p.usuario_id=$1 ORDER BY a.data_evento,a.hora_inicio`,[request.access.userId]);return response.json(rows);}catch(error){return next(error);}});

router.post('/activities',async(request,response,next)=>{try{const d=request.body;const link=await professorClass(request,d.turmaId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});if(!d.data||!d.titulo)return response.status(400).json({message:'Informe data e título.'});const weekday=new Date(String(d.data)+'T12:00:00').getDay();const schedule=await pool.query(`SELECT hora_inicio,hora_fim FROM horarios_professor WHERE professor_id=$1 AND turma_id=$2 AND dia_semana=$3 AND ativo=TRUE ORDER BY hora_inicio LIMIT 1`,[link.professor_id,d.turmaId,weekday]);if(!schedule.rows[0])return response.status(400).json({message:'O professor não possui horário cadastrado nessa turma para o dia escolhido.'});const h=schedule.rows[0];const {rows}=await pool.query(`INSERT INTO atividades_programadas(professor_id,turma_id,componente_curricular,tipo,titulo,descricao,data_evento,hora_inicio,hora_fim,valor,instrucoes,materiais) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,[link.professor_id,d.turmaId,link.componente_curricular,d.tipo||'Atividade',String(d.titulo).trim(),d.descricao||null,d.data,h.hora_inicio,h.hora_fim,d.valor?Number(d.valor):null,d.instrucoes||null,d.materiais||null]);return response.status(201).json(rows[0]);}catch(error){return next(error);}});

router.get('/questions',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT q.id,q.componente_curricular AS disciplina,q.tipo,q.enunciado,q.alternativas,q.resposta_gabarito AS "respostaGabarito",q.imagem,q.valor::float8,q.criado_em AS "criadoEm" FROM questoes_professor q JOIN professores p ON p.id=q.professor_id WHERE p.usuario_id=$1 ORDER BY q.criado_em DESC,q.id DESC`,[request.access.userId]);return response.json(rows);}catch(error){return next(error);}});
router.post('/questions',async(request,response,next)=>{try{const d=request.body;const link=await professorClass(request,d.turmaId);if(!link)return response.status(403).json({message:'Turma ou disciplina não atribuída ao professor.'});if(!String(d.enunciado||'').trim())return response.status(400).json({message:'Informe o enunciado da questão.'});const tipo=['Objetiva','Discursiva','Verdadeiro ou falso'].includes(d.tipo)?d.tipo:'Objetiva';const alternativas=Array.isArray(d.alternativas)?d.alternativas.map(x=>String(x).trim()).filter(Boolean):[];if(tipo==='Objetiva'&&alternativas.length<2)return response.status(400).json({message:'Questões objetivas precisam de pelo menos duas alternativas.'});const imagem=String(d.imagem||'').trim()||null;if(imagem&&imagem.length>2000000)return response.status(400).json({message:'A imagem deve ter no máximo 1,5 MB.'});if(imagem&&!/^https?:\/\//i.test(imagem)&&!/^data:image\//i.test(imagem))return response.status(400).json({message:'Informe um link de imagem válido ou selecione um arquivo.'});const {rows}=await pool.query(`INSERT INTO questoes_professor(professor_id,componente_curricular,tipo,enunciado,alternativas,resposta_gabarito,imagem,valor) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8) RETURNING id`,[link.professor_id,link.componente_curricular,tipo,String(d.enunciado).trim(),JSON.stringify(alternativas),d.respostaGabarito||null,imagem,Number(d.valor||1)]);return response.status(201).json(rows[0]);}catch(error){return next(error);}});
router.get('/exams',async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT pr.id,pr.turma_id AS "turmaId",t.nome AS turma,pr.componente_curricular AS disciplina,pr.titulo,pr.data_aplicacao AS data,pr.instrucoes,pr.status,TO_CHAR(a.hora_inicio,'HH24:MI') AS "horaInicio",TO_CHAR(a.hora_fim,'HH24:MI') AS "horaFim",COUNT(pq.questao_id)::INTEGER AS "quantidadeQuestoes",COALESCE(SUM(pq.valor),0)::float8 AS "valorTotal" FROM provas_professor pr JOIN professores p ON p.id=pr.professor_id JOIN turmas t ON t.id=pr.turma_id LEFT JOIN atividades_programadas a ON a.id=pr.atividade_id LEFT JOIN prova_questoes pq ON pq.prova_id=pr.id WHERE p.usuario_id=$1 GROUP BY pr.id,t.nome,a.hora_inicio,a.hora_fim ORDER BY pr.data_aplicacao DESC,pr.id DESC`,[request.access.userId]);return response.json(rows);}catch(error){return next(error);}});
router.post('/exams',async(request,response,next)=>{const client=await pool.connect();try{const d=request.body;const link=await professorClass(request,d.turmaId);if(!link)return response.status(403).json({message:'Turma não atribuída ao professor.'});const ids=(Array.isArray(d.questaoIds)?d.questaoIds:[]).map(Number).filter(Boolean);if(!d.data||!String(d.titulo||'').trim()||!ids.length)return response.status(400).json({message:'Informe título, data e selecione pelo menos uma questão.'});const weekday=new Date(String(d.data)+'T12:00:00').getDay();const grade=await pool.query(`SELECT hora_inicio,hora_fim FROM horarios_professor WHERE professor_id=$1 AND turma_id=$2 AND dia_semana=$3 AND ativo=TRUE ORDER BY hora_inicio LIMIT 1`,[link.professor_id,d.turmaId,weekday]);if(!grade.rows[0])return response.status(400).json({message:'Escolha uma data compatível com o horário desta turma.'});const qs=await pool.query(`SELECT id,valor::float8 FROM questoes_professor WHERE professor_id=$1 AND componente_curricular=$2 AND id=ANY($3::bigint[])`,[link.professor_id,link.componente_curricular,ids]);if(qs.rowCount!==ids.length)return response.status(403).json({message:'Uma ou mais questões não pertencem ao professor ou à disciplina.'});await client.query('BEGIN');const total=qs.rows.reduce((s,q)=>s+Number(q.valor),0);const activity=await client.query(`INSERT INTO atividades_programadas(professor_id,turma_id,componente_curricular,tipo,titulo,descricao,data_evento,hora_inicio,hora_fim,valor,instrucoes,materiais) VALUES($1,$2,$3,'Prova',$4,'Prova criada no banco de questões',$5,$6,$7,$8,$9,'Prova impressa') RETURNING id`,[link.professor_id,d.turmaId,link.componente_curricular,String(d.titulo).trim(),d.data,grade.rows[0].hora_inicio,grade.rows[0].hora_fim,Math.min(total,10),d.instrucoes||null]);const exam=await client.query(`INSERT INTO provas_professor(professor_id,turma_id,atividade_id,componente_curricular,titulo,data_aplicacao,instrucoes,status) VALUES($1,$2,$3,$4,$5,$6,$7,'Programada') RETURNING id`,[link.professor_id,d.turmaId,activity.rows[0].id,link.componente_curricular,String(d.titulo).trim(),d.data,d.instrucoes||null]);for(let i=0;i<qs.rows.length;i++)await client.query(`INSERT INTO prova_questoes(prova_id,questao_id,ordem,valor) VALUES($1,$2,$3,$4)`,[exam.rows[0].id,qs.rows[i].id,i+1,qs.rows[i].valor]);await client.query('COMMIT');return response.status(201).json({id:exam.rows[0].id,message:'Prova criada e adicionada ao calendário.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});
router.get('/exams/:id',async(request,response,next)=>{try{const exam=await pool.query(`SELECT pr.id,pr.turma_id AS "turmaId",t.nome AS turma,t.serie_ano AS "serieAno",t.turno,t.sala,pr.componente_curricular AS disciplina,pr.titulo,pr.data_aplicacao AS data,pr.instrucoes,pr.status,p.nome_completo AS professor,TO_CHAR(a.hora_inicio,'HH24:MI') AS "horaInicio",TO_CHAR(a.hora_fim,'HH24:MI') AS "horaFim" FROM provas_professor pr JOIN professores p ON p.id=pr.professor_id JOIN turmas t ON t.id=pr.turma_id LEFT JOIN atividades_programadas a ON a.id=pr.atividade_id WHERE pr.id=$1 AND p.usuario_id=$2`,[request.params.id,request.access.userId]);if(!exam.rows[0])return response.status(404).json({message:'Prova não encontrada.'});const {rows}=await pool.query(`SELECT q.id,q.tipo,q.enunciado,q.alternativas,q.imagem,pq.ordem,pq.valor::float8 FROM prova_questoes pq JOIN questoes_professor q ON q.id=pq.questao_id WHERE pq.prova_id=$1 ORDER BY pq.ordem`,[request.params.id]);return response.json({...exam.rows[0],questoes:rows,valorTotal:rows.reduce((s,q)=>s+Number(q.valor),0)});}catch(error){return next(error);}});

export default router;
