import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../database.js';
import { authenticate } from '../middlewares/auth.js';
import { loadAccessContext } from '../middlewares/access.js';

const router=Router();
const profiles=new Set(['Super Administrador','Secretário Municipal de Educação','Técnico da Secretaria de Educação','Secretaria Administrativa da Educação']);
const createSchema=z.object({tipo:z.enum(['Ofício','Memorando','Circular','Requerimento','Processo','Comunicação interna','Outros']),assunto:z.string().trim().min(3).max(255),descricao:z.string().trim().min(5).max(5000),origem:z.string().trim().min(2).max(180),prazo:z.iso.date().nullable().optional()});
const actionSchema=z.object({acao:z.enum(['classificar','encaminhar','receber_setor','responder','finalizar','arquivar']),classificacao:z.string().trim().max(100).nullable().optional(),destinatario:z.string().trim().max(180).nullable().optional(),setorDestino:z.string().trim().max(120).nullable().optional(),responsavelId:z.coerce.number().int().positive().nullable().optional(),prazo:z.iso.date().nullable().optional(),despacho:z.string().trim().min(3).max(4000)});
function fail(statusCode,message){const error=new Error(message);error.statusCode=statusCode;throw error;}
router.use(authenticate,loadAccessContext,(request,response,next)=>profiles.has(request.access?.perfil)?next():response.status(403).json({message:'Acesso exclusivo da gestão administrativa municipal.'}));

router.get('/references',async(_request,response,next)=>{try{const {rows}=await pool.query(`SELECT u.id,u.nome,t.nome AS perfil FROM usuarios u JOIN tipos_usuarios t ON t.id=u.tipo_usuario_id WHERE u.ativo=TRUE AND t.nome<>'Aluno' ORDER BY u.nome`);return response.json({responsaveis:rows});}catch(error){return next(error);}});

router.get('/',async(_request,response,next)=>{try{const {rows}=await pool.query(`SELECT d.id,d.numero,d.tipo,d.assunto,d.descricao,d.classificacao,d.origem,d.destinatario,d.setor_atual AS "setorAtual",d.responsavel_id AS "responsavelId",u.nome AS responsavel,d.status,d.prazo,d.criado_em AS "criadoEm",d.atualizado_em AS "atualizadoEm",COALESCE((SELECT JSON_AGG(JSON_BUILD_OBJECT('id',t.id,'evento',t.evento,'statusAnterior',t.status_anterior,'statusNovo',t.status_novo,'setorOrigem',t.setor_origem,'setorDestino',t.setor_destino,'destinatario',t.destinatario,'despacho',t.despacho,'usuario',tu.nome,'criadoEm',t.criado_em) ORDER BY t.criado_em) FROM tramitacoes_protocolo t LEFT JOIN usuarios tu ON tu.id=t.usuario_id WHERE t.documento_id=d.id),'[]'::json) AS timeline FROM documentos_protocolo d LEFT JOIN usuarios u ON u.id=d.responsavel_id ORDER BY d.criado_em DESC`);const open=rows.filter(item=>!['Finalizado','Arquivado'].includes(item.status));return response.json({dados:rows,resumo:{registrados:rows.length,emTramitacao:open.length,aguardandoResposta:rows.filter(item=>['Encaminhado','Em setor'].includes(item.status)).length,finalizados:rows.filter(item=>['Finalizado','Arquivado'].includes(item.status)).length}});}catch(error){return next(error);}});

router.post('/',async(request,response,next)=>{const client=await pool.connect();try{const data=createSchema.parse(request.body);await client.query('BEGIN');const seq=(await client.query(`SELECT nextval('protocolo_documentos_seq') AS value`)).rows[0].value;const number=`PROT-${new Date().getFullYear()}-${String(seq).padStart(6,'0')}`;const {rows}=await client.query(`INSERT INTO documentos_protocolo(numero,tipo,assunto,descricao,origem,prazo,criado_por) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[number,data.tipo,data.assunto,data.descricao,data.origem,data.prazo||null,request.access.userId]);await client.query(`INSERT INTO tramitacoes_protocolo(documento_id,usuario_id,evento,status_novo,despacho) VALUES($1,$2,'Registrado','Recebido','Documento registrado e número de protocolo gerado automaticamente.')`,[rows[0].id,request.access.userId]);await client.query('COMMIT');return response.status(201).json({id:rows[0].id,numero:number,message:'Documento protocolado com sucesso.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});

router.patch('/:id',async(request,response,next)=>{const client=await pool.connect();try{const id=z.coerce.number().int().positive().parse(request.params.id);const data=actionSchema.parse(request.body);await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM documentos_protocolo WHERE id=$1 FOR UPDATE',[id]);const document=rows[0];if(!document)fail(404,'Protocolo não encontrado.');if(document.status==='Arquivado')fail(409,'Um protocolo arquivado não pode receber novas tramitações.');const map={classificar:{allowed:['Recebido'],next:'Recebido',event:'Classificado'},encaminhar:{allowed:['Recebido','Respondido'],next:'Encaminhado',event:'Encaminhado'},receber_setor:{allowed:['Encaminhado'],next:'Em setor',event:'Recebido pelo setor'},responder:{allowed:['Em setor'],next:'Respondido',event:'Respondido'},finalizar:{allowed:['Respondido','Em setor'],next:'Finalizado',event:'Finalizado'},arquivar:{allowed:['Finalizado'],next:'Arquivado',event:'Arquivado'}};const rule=map[data.acao];if(!rule.allowed.includes(document.status))fail(409,`Ação indisponível para protocolo em “${document.status}”.`);if(data.acao==='classificar'&&!data.classificacao)fail(400,'Informe a classificação do documento.');if(data.acao==='encaminhar'&&(!data.destinatario||!data.setorDestino))fail(400,'Informe destinatário e setor de destino.');if(data.acao==='receber_setor'&&!data.responsavelId)fail(400,'Defina o responsável pelo acompanhamento.');const sector=data.setorDestino||document.setor_atual;await client.query(`UPDATE documentos_protocolo SET status=$1,classificacao=COALESCE($2,classificacao),destinatario=COALESCE($3,destinatario),setor_atual=COALESCE($4,setor_atual),responsavel_id=COALESCE($5,responsavel_id),prazo=COALESCE($6,prazo),atualizado_em=NOW(),finalizado_em=CASE WHEN $1='Finalizado' THEN NOW() ELSE finalizado_em END,arquivado_em=CASE WHEN $1='Arquivado' THEN NOW() ELSE arquivado_em END WHERE id=$7`,[rule.next,data.classificacao||null,data.destinatario||null,sector||null,data.responsavelId||null,data.prazo||null,id]);await client.query(`INSERT INTO tramitacoes_protocolo(documento_id,usuario_id,evento,status_anterior,status_novo,setor_origem,setor_destino,destinatario,despacho) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,request.access.userId,rule.event,document.status,rule.next,document.setor_atual||null,sector||null,data.destinatario||document.destinatario||null,data.despacho]);await client.query('COMMIT');return response.json({id,status:rule.next,message:'Tramitação registrada no histórico permanente.'});}catch(error){await client.query('ROLLBACK');return next(error);}finally{client.release();}});
export default router;
