export const migrations = [
  '02_criar_tabelas.sql', '03_relacionamentos.sql', '04_dados_iniciais.sql',
  '06_autenticacao_usuarios.sql', '07_api_autenticacao.sql', '08_transporte_escolar.sql',
  '09_vinculo_diretor_escola.sql', '10_veiculos_propriedade.sql', '11_funcionario_educacao.sql',
  '12_perfis_colaboradores.sql', '13_auditoria_recursos_escolares.sql',
  '14_gestao_financeira_escolar.sql', '15_transporte_itinerarios_alunos_manutencoes.sql',
  '16_seguranca_recuperacao_auditoria.sql', '17_nucleo_academico.sql',
  '18_unidades_rede_municipal.sql', '19_detalhes_escolas.sql',
  '20_detalhes_profissionais_escolares.sql', '21_importacao_cm_antonio_joaquim.sql',
  '22_perfil_vice_diretor.sql', '23_email_usuario_opcional.sql',
  '24_perfis_funcionarios_educacao.sql', '25_hierarquia_acesso_profissionais.sql',
  '26_cadastro_funcional_completo.sql', '27_perfis_acesso_siedu.sql',
  '28_usuario_teste_secretario.sql', '29_usuario_teste_secretario_exclusivo.sql',
  '30_usuario_teste_superintendente.sql', '31_usuario_teste_coordenador.sql',
  '32_usuario_teste_diretor.sql', '33_usuario_teste_professor.sql',
  '34_historico_aluno_professor.sql', '35_vinculo_turma_professor_teste.sql',
  '36_dados_teste_turmas_professor.sql', '37_diario_classe_professor.sql',
  '38_avaliacoes_notas_professor.sql', '39_planejamento_aula_professor.sql',
  '40_atividades_avaliacoes_calendario.sql', '41_banco_questoes_provas.sql',
  '42_materiais_aula.sql', '43_competencias_relatorios_professor.sql',
  '44_calendario_escolar_professor.sql', '45_eventos_alunos_calendario.sql',
  '46_portal_aluno.sql', '47_aprendizagem_ciclos_trilhas_saeb.sql',
  '48_calendario_escolar_aluno.sql', '49_portal_professor_completo.sql',
  '50_gestao_municipal_integrada.sql',
  '51_serie_historica_ideb_pindobacu.sql',
  '52_fluxo_demandas_escolares.sql',
  '53_usuarios_teste_fluxo_demandas.sql',
  '54_bloquear_usuarios_teste_fluxo_demandas.sql',
];
